name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Pytest
        run: pytest
